### ISSUE TITLE
bench compile warning with latest sgx-step version on Ubuntu 20.04

### ISSUE THREAD

**Issue by Neo-Outis** [jovanbulck/sgx-step#33] opened 2020-10-11 14:23 UTC
Hi, 

I just tried to run bench project with your latest version of sgx-step on my new laptop. And when I compile the bench project, I got following warning:
aep_trampoline.S: Assembler messages:
aep_trampoline.S:60 Warning: no instruction mnemonic suffix given and no register operands; using default for 'add'

And I also got same warning from irq_entry.S:36 .
Then my laptop was frozen and I had to restart my laptop.(This happens whenever I run the bench project)

So far, I have tried with it on two machines which had skylake and whisky model. Both systems are ubuntu 20.04.

Would it be the problem related to ubuntu 20 ? Could you gave me some suggestions on how to fix it ?

Thanks in advance.

Regards

**Comment by jovanbulck** [comment] 2020-10-13 15:35
Hi Neo,

> I just tried to run bench project with your latest version of sgx-step on my new laptop. And when I compile the bench project, I got following warning:

Thanks for reporting the warnings,I fixed them in the above commit. I am also in the process of setting up continuous integration to automatically build SGX-Step on both Ubuntu 18.04/20.04. You can normally see the latest build here:

https://travis-ci.org/github/jovanbulck/sgx-step

>  Then my laptop was frozen and I had to restart my laptop.(This happens whenever I run the bench project)

Not sure what you mean? The above warnings are normally harmless, so I don't expect they're the cause why your laptop freezes. I suspect something goes wrong w the timer and you should configure the interval? Also make sure you pass all the kernel boot params etc. Did you run `app/idt` and `app/cpl` successfully to make sure the general setup works before running `app/bench`? Did you get any error log?

> Would it be the problem related to ubuntu 20 ? Could you gave me some suggestions on how to fix it ?

I don't have a machine with 20.04 atm (I'm running 18.04 myself), so cannot say for sure. Normally, I expect things to work similarly on 18.04 and 20.04 though.

Let me know how things work on your end, so we can hopefully fix and close this issue?

**Comment by bloaryth** [comment] 2020-11-16 11:10
I was faced with the same issue, but now I have fixed it by adding new Linux kernel parameters. I didn't notice the project has been updated. The kernel parameters I was missing are `nmi_watchdog=0 nosmap nosmep clearcpuid=514`. Hope that would help.

**Comment by Neo-Outis** [comment] 2020-11-16 11:18
Hi bloaryth,

Are you using ubuntu 20.04 ? Currently sgx-step works fluently for me in the tty mode. When I was in the UI mode, my laptop sometimes will freeze when I am using browsers.

**Closed** 2020-12-01 09:19 UTC
